const COUNTER_CATALOG = [
  // === Burrowing (5) ===
  {
    id: 'counter_burrowing_01',
    name: 'Foundations Upon Shifting Ground',
    topic: 'counter',
    traitId: 'burrowing',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'foundation_stabilization',
    abilityName: 'Foundation Stabilization',
    abilityDescription: 'Prevents burrowing creatures from undermining buildings and fortifications.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_burrowing_02',
    name: 'The Sanctity of Earth: Blessing What Lies Below',
    topic: 'counter',
    traitId: 'burrowing',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'blessed_soil_ward',
    abilityName: 'Blessed Soil Ward',
    abilityDescription: 'Creates a sacred barrier that impedes burrowing movement through protected ground.',
    counterRole: 'priest',
    counterForm: 'ward',
  },
  {
    id: 'counter_burrowing_03',
    name: 'Creatures of the Underdark: Habits and Habitats',
    topic: 'counter',
    traitId: 'burrowing',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_burrow_patterns',
    abilityName: 'Identify Burrow Patterns',
    abilityDescription: 'Reveals the tunneling routes and weak points in burrow networks.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_burrowing_04',
    name: 'Deep Roots and Deeper Problems',
    topic: 'counter',
    traitId: 'burrowing',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_burrowing_05',
    name: 'Soil Compaction Techniques for Fortification',
    topic: 'counter',
    traitId: 'burrowing',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'compact_soil_fortify',
    abilityName: 'Compact Soil Fortify',
    abilityDescription: 'Hardens earth to make tunneling prohibitively difficult and dangerous.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },

  // === Armored (5) ===
  {
    id: 'counter_armored_01',
    name: 'The Point of Entry: Where Shells Are Thinnest',
    topic: 'counter',
    traitId: 'armored',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'weak_point_targeting',
    abilityName: 'Weak Point Targeting',
    abilityDescription: 'Identifies and exploits gaps and joints in armored creatures for maximum damage.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_armored_02',
    name: 'Metallurgy of Penetrating Implements',
    topic: 'counter',
    traitId: 'armored',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'forge_piercing_tools',
    abilityName: 'Forge Piercing Tools',
    abilityDescription: 'Crafts weapons specifically designed to penetrate and break through heavy armor.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_armored_03',
    name: 'On Carapace: Structure and Failure Under Stress',
    topic: 'counter',
    traitId: 'armored',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'analyze_armor_structure',
    abilityName: 'Analyze Armor Structure',
    abilityDescription: 'Reveals structural weaknesses in exoskeletons and the stress points most likely to fracture.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_armored_04',
    name: 'The Unbreakable: Legends of Impervious Beasts',
    topic: 'counter',
    traitId: 'armored',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_armored_05',
    name: 'Leverage and Force Concentration in Small Tools',
    topic: 'counter',
    traitId: 'armored',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'leverage_tools_craft',
    abilityName: 'Leverage Tools Craft',
    abilityDescription: 'Designs compact tools that concentrate force to break through even the thickest plating.',
    counterRole: 'engineer',
    counterForm: 'build',
  },

  // === Flying (5) ===
  {
    id: 'counter_flying_01',
    name: 'Weighted Nets and Their Deployment from Height',
    topic: 'counter',
    traitId: 'flying',
    hint: 'Engineer:Deploy',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'deploy_heavy_nets',
    abilityName: 'Deploy Heavy Nets',
    abilityDescription: 'Launches weighted nets that entangle and ground flying creatures mid-flight.',
    counterRole: 'engineer',
    counterForm: 'deploy',
  },
  {
    id: 'counter_flying_02',
    name: 'Prayers Against What Descends From Above',
    topic: 'counter',
    traitId: 'flying',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'anti_flight_ward',
    abilityName: 'Anti-Flight Ward',
    abilityDescription: 'Creates a spiritual barrier that hinders flight and slows descent for airborne threats.',
    counterRole: 'priest',
    counterForm: 'ward',
  },
  {
    id: 'counter_flying_03',
    name: 'Winged Threats: Observation and Classification',
    topic: 'counter',
    traitId: 'flying',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'catalog_fliers',
    abilityName: 'Catalog Fliers',
    abilityDescription: 'Documents flight patterns and wing mechanics to predict movement and vulnerability.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_flying_04',
    name: 'On the Grace of Birds and the Envy of the Earthbound',
    topic: 'counter',
    traitId: 'flying',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_flying_05',
    name: 'Elevation Defence: Holding Rooftops and Parapets',
    topic: 'counter',
    traitId: 'flying',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'high_ground_defense',
    abilityName: 'High Ground Defense',
    abilityDescription: 'Tactical positioning that leverages height advantage to combat airborne attackers.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },

  // === Swarming (5) ===
  {
    id: 'counter_swarming_01',
    name: 'Breaking the Herd: Isolating Coordinated Threats',
    topic: 'counter',
    traitId: 'swarming',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'isolate_swarms',
    abilityName: 'Isolate Swarms',
    abilityDescription: 'Breaks up coordinated enemy groups by separating individuals and disrupting communication.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_swarming_02',
    name: 'Wards of Dispersal and Scattering',
    topic: 'counter',
    traitId: 'swarming',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'dispersion_ward',
    abilityName: 'Dispersion Ward',
    abilityDescription: 'Creates a repulsive field that scatters coordinated groups and prevents tight formations.',
    counterRole: 'priest',
    counterForm: 'ward',
  },
  {
    id: 'counter_swarming_03',
    name: 'Swarm Behaviour in Mist-Touched Fauna',
    topic: 'counter',
    traitId: 'swarming',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'analyze_swarm_behavior',
    abilityName: 'Analyze Swarm Behavior',
    abilityDescription: 'Studies coordinated creature behavior to predict patterns and identify hive leaders.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_swarming_04',
    name: 'The Strength of Numbers: Why Groups Prevail',
    topic: 'counter',
    traitId: 'swarming',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_swarming_05',
    name: 'Choke Points and Funnelling: A Tactical Guide',
    topic: 'counter',
    traitId: 'swarming',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'create_choke_points',
    abilityName: 'Create Choke Points',
    abilityDescription: 'Modifies terrain and structures to force large groups into narrow passages where coordination fails.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },

  // === Charging (5) ===
  {
    id: 'counter_charging_01',
    name: 'Receiving the Charge: What Stands and What Falls',
    topic: 'counter',
    traitId: 'charging',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'build_charge_barriers',
    abilityName: 'Build Charge Barriers',
    abilityDescription: 'Constructs fixed structures that withstand charge impacts and disperse kinetic force.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_charging_02',
    name: 'The Matador\'s Principle: Redirecting Momentum',
    topic: 'counter',
    traitId: 'charging',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'redirect_momentum',
    abilityName: 'Redirect Momentum',
    abilityDescription: 'Uses enemy force against them by sidestepping and redirecting charge momentum into terrain.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_charging_03',
    name: 'Velocity and Mass: When Speed Becomes a Weapon',
    topic: 'counter',
    traitId: 'charging',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'analyze_charge_physics',
    abilityName: 'Analyze Charge Physics',
    abilityDescription: 'Studies the physics of charging creatures to calculate impact points and breaking distances.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_charging_04',
    name: 'The Unstoppable: Tales of Beasts That Never Slowed',
    topic: 'counter',
    traitId: 'charging',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_charging_05',
    name: 'Angled Barriers and Deflection Walls',
    topic: 'counter',
    traitId: 'charging',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'deflect_charges',
    abilityName: 'Deflect Charges',
    abilityDescription: 'Angles walls and barriers to redirect charging momentum sideways into obstacles.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },

  // === Grappling (5) ===
  {
    id: 'counter_grappling_01',
    name: 'Escape the Hold: Breaking Free of Superior Grip',
    topic: 'counter',
    traitId: 'grappling',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'grip_escape',
    abilityName: 'Grip Escape',
    abilityDescription: 'Techniques to break free from grappling holds using leverage and pressure points.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_grappling_02',
    name: 'Slick Surfaces and Their Military Applications',
    topic: 'counter',
    traitId: 'grappling',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'slick_surface_build',
    abilityName: 'Slick Surface Build',
    abilityDescription: 'Treats armor and terrain with oils to prevent grappling creatures from maintaining hold.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_grappling_03',
    name: 'Tentacle and Tendril: Anatomy of the Grasping Limb',
    topic: 'counter',
    traitId: 'grappling',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_graspers',
    abilityName: 'Identify Graspers',
    abilityDescription: 'Catalogs grappling appendages to find cut points and vulnerable connection joints.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_grappling_04',
    name: 'The Embrace of the Deep: Maritime Horrors',
    topic: 'counter',
    traitId: 'grappling',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_grappling_05',
    name: 'Severing Blades: Designed for Limb Removal',
    topic: 'counter',
    traitId: 'grappling',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'forge_severing_blades',
    abilityName: 'Forge Severing Blades',
    abilityDescription: 'Crafts specialized cutting implements to sever grappling limbs cleanly.',
    counterRole: 'engineer',
    counterForm: 'build',
  },

  // === Camouflaged (5) ===
  {
    id: 'counter_camouflaged_01',
    name: 'Wards of Revelation: Making the Hidden Seen',
    topic: 'counter',
    traitId: 'camouflaged',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'reveal_ward',
    abilityName: 'Reveal Ward',
    abilityDescription: 'Creates a blessed field that compels hidden creatures to become visible within its radius.',
    counterRole: 'priest',
    counterForm: 'ward',
  },
  {
    id: 'counter_camouflaged_02',
    name: 'Tripwire Systems for Perimeter Detection',
    topic: 'counter',
    traitId: 'camouflaged',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'tripwire_detection',
    abilityName: 'Tripwire Detection',
    abilityDescription: 'Builds sensitive wire networks that trigger alerts when invisible or concealed creatures pass.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_camouflaged_03',
    name: 'Patterns of Concealment in Mist Fauna',
    topic: 'counter',
    traitId: 'camouflaged',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_camouflage',
    abilityName: 'Identify Camouflage',
    abilityDescription: 'Studies concealment patterns and environmental breaks that expose hidden creatures.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_camouflaged_04',
    name: 'The Art of Hiding: Camouflage in the Natural World',
    topic: 'counter',
    traitId: 'camouflaged',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_camouflaged_05',
    name: 'Dust and Powder: Marking What Cannot Be Seen',
    topic: 'counter',
    traitId: 'camouflaged',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'powder_marking',
    abilityName: 'Powder Marking',
    abilityDescription: 'Uses fine powders and dust clouds to silhouette and track invisible or hidden enemies.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },

  // === Heat Aura (5) ===
  {
    id: 'counter_heat_aura_01',
    name: 'Water and Its Forms: From Mist to Ice',
    topic: 'counter',
    traitId: 'heat_aura',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_water_forms',
    abilityName: 'Invoke Water Forms',
    abilityDescription: 'Channels water and conjures steam to cool intense heat and protect against thermal damage.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_heat_aura_02',
    name: 'Thermal Regulation in Enclosed Spaces',
    topic: 'counter',
    traitId: 'heat_aura',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'build_heat_sinks',
    abilityName: 'Build Heat Sinks',
    abilityDescription: 'Constructs thermal dampening structures that dissipate and redirect heat away from defenders.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_heat_aura_03',
    name: 'The Nature of Elemental Heat and Its Boundaries',
    topic: 'counter',
    traitId: 'heat_aura',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'measure_heat_limits',
    abilityName: 'Measure Heat Limits',
    abilityDescription: 'Catalogs thermal phenomena to identify safe distances and limits of heat aura effects.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_heat_aura_04',
    name: 'Ash and Ember: A Meditation on Impermanence',
    topic: 'counter',
    traitId: 'heat_aura',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_heat_aura_05',
    name: 'Quenching Techniques for Superheated Materials',
    topic: 'counter',
    traitId: 'heat_aura',
    hint: 'Engineer:Deploy',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'deploy_quench',
    abilityName: 'Deploy Quench',
    abilityDescription: 'Deploys rapid cooling agents that rapidly lower temperatures and stop thermal transfer.',
    counterRole: 'engineer',
    counterForm: 'deploy',
  },

  // === Electric (5) ===
  {
    id: 'counter_electric_01',
    name: 'Conducting Away the Storm: Principles of Grounding',
    topic: 'counter',
    traitId: 'electric',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'build_grounding',
    abilityName: 'Build Grounding',
    abilityDescription: 'Constructs grounding systems that safely dissipate electrical charge into the earth.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_electric_02',
    name: 'The Insulated Warrior: Fighting in Charged Conditions',
    topic: 'counter',
    traitId: 'electric',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'insulated_combat',
    abilityName: 'Insulated Combat',
    abilityDescription: 'Teaches techniques and materials to resist electrical conduction during active combat.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_electric_03',
    name: 'Cataloguing Creatures of Spark and Arc',
    topic: 'counter',
    traitId: 'electric',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'catalog_electric_fauna',
    abilityName: 'Catalog Electric Fauna',
    abilityDescription: 'Documents electrical creatures and their discharge patterns to predict strikes.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_electric_04',
    name: 'Ball Lightning and Other Atmospheric Curiosities',
    topic: 'counter',
    traitId: 'electric',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_electric_05',
    name: 'Materials That Refuse the Current',
    topic: 'counter',
    traitId: 'electric',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'insulating_materials',
    abilityName: 'Insulating Materials',
    abilityDescription: 'Modifies armor and weapons with non-conductive materials that block electrical transfer.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },

  // === Frost Touch (5) ===
  {
    id: 'counter_frost_touch_01',
    name: 'Braziers of Endurance: Sustained Heat in Hostile Conditions',
    topic: 'counter',
    traitId: 'frost_touch',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'build_heat_braziers',
    abilityName: 'Build Heat Braziers',
    abilityDescription: 'Constructs portable heat sources that maintain warmth against extreme cold auras.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_frost_touch_02',
    name: 'The Inner Fire: Spiritual Warmth Against Unnatural Cold',
    topic: 'counter',
    traitId: 'frost_touch',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_inner_warmth',
    abilityName: 'Invoke Inner Warmth',
    abilityDescription: 'Invokes spiritual heat that radiates from within to resist supernatural cold effects.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_frost_touch_03',
    name: 'Cold-Blooded: Creatures That Weaponise Low Temperatures',
    topic: 'counter',
    traitId: 'frost_touch',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_frost_creatures',
    abilityName: 'Identify Frost Creatures',
    abilityDescription: 'Studies cold-adapted creatures to learn their thermal thresholds and weaknesses.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_frost_touch_04',
    name: 'Winter Recipes for the Homesick Traveller',
    topic: 'counter',
    traitId: 'frost_touch',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_frost_touch_05',
    name: 'Layered Garments and Thermal Retention Theory',
    topic: 'counter',
    traitId: 'frost_touch',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'thermal_layering',
    abilityName: 'Thermal Layering',
    abilityDescription: 'Teaches proper insulation techniques using layered clothing and thermal materials.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },

  // === Corrosive (5) ===
  {
    id: 'counter_corrosive_01',
    name: 'Cleansing the Tainted: Rites of Purification',
    topic: 'counter',
    traitId: 'corrosive',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_purification',
    abilityName: 'Invoke Purification',
    abilityDescription: 'Invokes sacred rites that purify and neutralize corrosive substances and damage.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_corrosive_02',
    name: 'Resistant Coatings for Tools and Armour',
    topic: 'counter',
    traitId: 'corrosive',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'apply_resistant_coatings',
    abilityName: 'Apply Resistant Coatings',
    abilityDescription: 'Forges and applies protective coatings that resist corrosive deterioration.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_corrosive_03',
    name: 'A Study of Noxious Substances and Their Effects',
    topic: 'counter',
    traitId: 'corrosive',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'analyze_corrosives',
    abilityName: 'Analyze Corrosives',
    abilityDescription: 'Studies corrosive substances to identify composition and appropriate neutralization methods.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_corrosive_04',
    name: 'The Poison Garden: Beauty in Lethality',
    topic: 'counter',
    traitId: 'corrosive',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_corrosive_05',
    name: 'What the Body Rejects: On Natural Immunity',
    topic: 'counter',
    traitId: 'corrosive',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'natural_resistance',
    abilityName: 'Natural Resistance',
    abilityDescription: 'Hardens the body through conditioning to build natural immunity to corrosive damage.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },

  // === Shadow Cloak (5) ===
  {
    id: 'counter_shadow_cloak_01',
    name: 'Luminous Wards: Spiritual Light That Banishes Darkness',
    topic: 'counter',
    traitId: 'shadow_cloak',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'luminous_ward',
    abilityName: 'Luminous Ward',
    abilityDescription: 'Creates blessed light that dispels shadow cloaking and reveals concealed enemies.',
    counterRole: 'priest',
    counterForm: 'ward',
  },
  {
    id: 'counter_shadow_cloak_02',
    name: 'Flare Mechanisms: Sudden Light in Desperate Moments',
    topic: 'counter',
    traitId: 'shadow_cloak',
    hint: 'Engineer:Deploy',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'deploy_flares',
    abilityName: 'Deploy Flares',
    abilityDescription: 'Deploys bright flare devices that suddenly illuminate shadowed areas and blind users of darkness.',
    counterRole: 'engineer',
    counterForm: 'deploy',
  },
  {
    id: 'counter_shadow_cloak_03',
    name: 'The Taxonomy of Darkness: Cataloguing Shadow Creatures',
    topic: 'counter',
    traitId: 'shadow_cloak',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_shadow_creatures',
    abilityName: 'Identify Shadow Creatures',
    abilityDescription: 'Documents shadow creatures and dark phenomena to predict manifestation patterns.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_shadow_cloak_04',
    name: 'Shadows on the Wall: A Children\'s Guide to Not Being Afraid',
    topic: 'counter',
    traitId: 'shadow_cloak',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_shadow_cloak_05',
    name: 'Reflective Surfaces as Force Multipliers for Light',
    topic: 'counter',
    traitId: 'shadow_cloak',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'modify_reflective_surfaces',
    abilityName: 'Modify Reflective Surfaces',
    abilityDescription: 'Modifies armor and structures with reflective materials to amplify light and dispel shadows.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },

  // === Spore Cloud (5) ===
  {
    id: 'counter_spore_cloud_01',
    name: 'Wind Channels and Directed Airflow in Settlements',
    topic: 'counter',
    traitId: 'spore_cloud',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'modify_airflow',
    abilityName: 'Modify Airflow',
    abilityDescription: 'Modifies structures and terrain to create wind patterns that disperse spore clouds.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },
  {
    id: 'counter_spore_cloud_02',
    name: 'Breath Discipline: Fighting in Foul Conditions',
    topic: 'counter',
    traitId: 'spore_cloud',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'breath_control',
    abilityName: 'Breath Control',
    abilityDescription: 'Teaches breathing techniques to minimize inhalation of toxic spores during combat.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_spore_cloud_03',
    name: 'Spore Biology: Dispersal, Toxicity, and Countermeasures',
    topic: 'counter',
    traitId: 'spore_cloud',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_spores',
    abilityName: 'Identify Spores',
    abilityDescription: 'Studies spore composition and dispersal to develop targeted countermeasures.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_spore_cloud_04',
    name: 'My Season Among the Drifters: A Personal Account',
    topic: 'counter',
    traitId: 'spore_cloud',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_spore_cloud_05',
    name: 'Masks and Filters: Practical Respiratory Protection',
    topic: 'counter',
    traitId: 'spore_cloud',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'build_respirators',
    abilityName: 'Build Respirators',
    abilityDescription: 'Constructs masks and filters that block inhalation of toxic spores and airborne threats.',
    counterRole: 'engineer',
    counterForm: 'build',
  },

  // === Phasing (5) ===
  {
    id: 'counter_phasing_01',
    name: 'Anchoring the Immaterial: Binding What Shifts',
    topic: 'counter',
    traitId: 'phasing',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_anchoring',
    abilityName: 'Invoke Anchoring',
    abilityDescription: 'Invokes rituals that anchor phasing creatures to the material plane, preventing phasing.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_phasing_02',
    name: 'Seeing What Is Not Fully There',
    topic: 'counter',
    traitId: 'phasing',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'track_phasing',
    abilityName: 'Track Phasing',
    abilityDescription: 'Teaches combat awareness to anticipate and strike phasing threats before they shift.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_phasing_03',
    name: 'Between Here and Elsewhere: The Nature of Phasing',
    topic: 'counter',
    traitId: 'phasing',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'understand_phasing',
    abilityName: 'Understand Phasing',
    abilityDescription: 'Studies phasing mechanics to identify the moments creatures become material and vulnerable.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_phasing_04',
    name: 'Ghost Stories of the Old Settlements',
    topic: 'counter',
    traitId: 'phasing',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_phasing_05',
    name: 'Consecrated Ground and Its Effect on the Intangible',
    topic: 'counter',
    traitId: 'phasing',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'consecrate_ground',
    abilityName: 'Consecrate Ground',
    abilityDescription: 'Consecrates ground to prevent phasing creatures from entering or shifting through blessed areas.',
    counterRole: 'priest',
    counterForm: 'ward',
  },

  // === Regenerating (5) ===
  {
    id: 'counter_regenerating_01',
    name: 'The Wound That Will Not Close: On Cauterisation',
    topic: 'counter',
    traitId: 'regenerating',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'cauterize_wounds',
    abilityName: 'Cauterize Wounds',
    abilityDescription: 'Burns wounds immediately to prevent regenerating creatures from healing damage.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_regenerating_02',
    name: 'Burning Pitch: Preparation and Tactical Application',
    topic: 'counter',
    traitId: 'regenerating',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'forge_burning_pitch',
    abilityName: 'Forge Burning Pitch',
    abilityDescription: 'Prepares flammable pitch that applies persistent heat to prevent wound closure.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_regenerating_03',
    name: 'Flesh That Remembers: Studies in Rapid Healing',
    topic: 'counter',
    traitId: 'regenerating',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'understand_regeneration',
    abilityName: 'Understand Regeneration',
    abilityDescription: 'Studies regeneration biology to find critical organs and healing nexuses to target.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_regenerating_04',
    name: 'The Hydra Problem: Cutting Heads That Grow Back',
    topic: 'counter',
    traitId: 'regenerating',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_regenerating_05',
    name: 'Sustained Assault Doctrines for Persistent Threats',
    topic: 'counter',
    traitId: 'regenerating',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'continuous_assault',
    abilityName: 'Continuous Assault',
    abilityDescription: 'Teaches relentless attack patterns that overwhelm regeneration faster than healing occurs.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },

  // === Sonic (5) ===
  {
    id: 'counter_sonic_01',
    name: 'Silence as a Weapon: Dampening Hostile Sound',
    topic: 'counter',
    traitId: 'sonic',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'sound_dampening',
    abilityName: 'Sound Dampening',
    abilityDescription: 'Modifies structures and armor with sound-absorbing materials to reduce sonic damage.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },
  {
    id: 'counter_sonic_02',
    name: 'The Unshaken Mind: Resisting What Assaults the Spirit',
    topic: 'counter',
    traitId: 'sonic',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'mental_fortitude',
    abilityName: 'Mental Fortitude',
    abilityDescription: 'Teaches mental discipline to resist sonic assault and maintain combat effectiveness.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_sonic_03',
    name: 'Frequencies of the Mist: Acoustic Phenomena',
    topic: 'counter',
    traitId: 'sonic',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'catalog_frequencies',
    abilityName: 'Catalog Frequencies',
    abilityDescription: 'Documents sonic frequencies to identify resonant vulnerabilities in creatures.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_sonic_04',
    name: 'Music of the Spheres: Harmonic Theory',
    topic: 'counter',
    traitId: 'sonic',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_sonic_05',
    name: 'Wards of Inner Calm and Outer Silence',
    topic: 'counter',
    traitId: 'sonic',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'silence_ward',
    abilityName: 'Silence Ward',
    abilityDescription: 'Creates a blessed field of silence that dampens sonic attacks and stabilizes hearing.',
    counterRole: 'priest',
    counterForm: 'ward',
  },

  // === Fear Aura (5) ===
  {
    id: 'counter_fear_aura_01',
    name: 'The Rite of Courage: Prayers That Steel the Heart',
    topic: 'counter',
    traitId: 'fear_aura',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_courage',
    abilityName: 'Invoke Courage',
    abilityDescription: 'Invokes sacred rites that grant spiritual fortitude against fear and dread.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_fear_aura_02',
    name: 'Iron Will: Mental Conditioning for Extreme Conditions',
    topic: 'counter',
    traitId: 'fear_aura',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'steel_resolve',
    abilityName: 'Steel Resolve',
    abilityDescription: 'Trains the mind through extreme conditioning to resist fear-based manipulation.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_fear_aura_03',
    name: 'The Anatomy of Dread: How Fear Enters the Mind',
    topic: 'counter',
    traitId: 'fear_aura',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'analyze_fear',
    abilityName: 'Analyze Fear',
    abilityDescription: 'Studies fear mechanics to identify sources and develop resistance strategies.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_fear_aura_04',
    name: 'Bedtime Stories for Nervous Children',
    topic: 'counter',
    traitId: 'fear_aura',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_fear_aura_05',
    name: 'Incense of Clarity: Aromatics That Calm the Mind',
    topic: 'counter',
    traitId: 'fear_aura',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'forge_clarity_incense',
    abilityName: 'Forge Clarity Incense',
    abilityDescription: 'Crafts aromatic compounds that calm the mind and block fear-inducing thoughts.',
    counterRole: 'engineer',
    counterForm: 'build',
  },

  // === Life Drain (5) ===
  {
    id: 'counter_life_drain_01',
    name: 'Soul Ward: Protecting the Vital Essence',
    topic: 'counter',
    traitId: 'life_drain',
    hint: 'Priest:Ward',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'soul_ward',
    abilityName: 'Soul Ward',
    abilityDescription: 'Creates a blessed barrier that shields vital essence from draining effects.',
    counterRole: 'priest',
    counterForm: 'ward',
  },
  {
    id: 'counter_life_drain_02',
    name: 'Vital Sealing Salves and Their Preparation',
    topic: 'counter',
    traitId: 'life_drain',
    hint: 'Engineer:Build',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'forge_sealing_salves',
    abilityName: 'Forge Sealing Salves',
    abilityDescription: 'Prepares protective salves that seal wounds and prevent life force from being drawn out.',
    counterRole: 'engineer',
    counterForm: 'build',
  },
  {
    id: 'counter_life_drain_03',
    name: 'Parasitism in the Mist: Creatures That Feed on the Living',
    topic: 'counter',
    traitId: 'life_drain',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'identify_parasites',
    abilityName: 'Identify Parasites',
    abilityDescription: 'Studies parasitic creatures to understand their feeding mechanisms and vulnerabilities.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_life_drain_04',
    name: 'The Fading: Accounts of Those Who Grew Thin and Pale',
    topic: 'counter',
    traitId: 'life_drain',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_life_drain_05',
    name: 'Rotation Tactics: Fresh Fighters Against Attrition',
    topic: 'counter',
    traitId: 'life_drain',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'rotation_tactics',
    abilityName: 'Rotation Tactics',
    abilityDescription: 'Teaches strategic fighter rotation to ensure fresh troops prevent cumulative life drain.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },

  // === Mimic (5) ===
  {
    id: 'counter_mimic_01',
    name: 'The Art of the Feint: Deception in Combat',
    topic: 'counter',
    traitId: 'mimic',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'strategic_feints',
    abilityName: 'Strategic Feints',
    abilityDescription: 'Uses deceptive maneuvers that confuse mimics and expose them through false reactions.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_mimic_02',
    name: 'Chaos as Strategy: The Blessing of Unpredictability',
    topic: 'counter',
    traitId: 'mimic',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_chaos',
    abilityName: 'Invoke Chaos',
    abilityDescription: 'Invokes chaotic blessings that keep mimics from predicting actions or intentions.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_mimic_03',
    name: 'Adaptive Behaviour in Mist Fauna',
    topic: 'counter',
    traitId: 'mimic',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'study_adaptation',
    abilityName: 'Study Adaptation',
    abilityDescription: 'Studies how mimics learn and adapt to discover their observation patterns.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_mimic_04',
    name: 'The Mirror and the Mask: A Theatrical History',
    topic: 'counter',
    traitId: 'mimic',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_mimic_05',
    name: 'Randomised Patrol Patterns and Unpredictable Defences',
    topic: 'counter',
    traitId: 'mimic',
    hint: 'Engineer:Modify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'randomize_patterns',
    abilityName: 'Randomize Patterns',
    abilityDescription: 'Modifies defensive routines and patrol patterns to prevent mimics from learning and predicting positions.',
    counterRole: 'engineer',
    counterForm: 'modify',
  },

  // === Hive Mind (5) ===
  {
    id: 'counter_hive_mind_01',
    name: 'The Severance Rite: Cutting Bonds That Bind',
    topic: 'counter',
    traitId: 'hive_mind',
    hint: 'Priest:Invoke',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'invoke_severance',
    abilityName: 'Invoke Severance',
    abilityDescription: 'Invokes a rite that severs mental bonds connecting individuals to the hive consciousness.',
    counterRole: 'priest',
    counterForm: 'invoke',
  },
  {
    id: 'counter_hive_mind_02',
    name: 'Simultaneous Strike Doctrine: Hitting Many at Once',
    topic: 'counter',
    traitId: 'hive_mind',
    hint: 'Soldier:Doctrine',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'coordinated_strikes',
    abilityName: 'Coordinated Strikes',
    abilityDescription: 'Teaches synchronized multi-target attacks that kill hive members faster than consciousness can adapt.',
    counterRole: 'soldier',
    counterForm: 'doctrine',
  },
  {
    id: 'counter_hive_mind_03',
    name: 'Collective Intelligence in Mist Organisms',
    topic: 'counter',
    traitId: 'hive_mind',
    hint: 'Scholar:Identify',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'understand_hives',
    abilityName: 'Understand Hives',
    abilityDescription: 'Studies hive consciousness structures to identify central nodes and communication weaknesses.',
    counterRole: 'scholar',
    counterForm: 'identify',
  },
  {
    id: 'counter_hive_mind_04',
    name: 'Ants, Bees, and Other Social Insects: A Survey',
    topic: 'counter',
    traitId: 'hive_mind',
    hint: 'DUD',
    language: 'common',
    discoverable: 'common',
    tier: 0,
    abilityId: null,
    abilityName: null,
    abilityDescription: null,
    counterRole: null,
    counterForm: null,
  },
  {
    id: 'counter_hive_mind_05',
    name: 'Signal Jamming: Disrupting Communication Between Threats',
    topic: 'counter',
    traitId: 'hive_mind',
    hint: 'Engineer:Deploy',
    language: 'common',
    discoverable: 'common',
    tier: 1,
    abilityId: 'deploy_jammers',
    abilityName: 'Deploy Jammers',
    abilityDescription: 'Deploys signal-jamming devices that disrupt mental communication between hive members.',
    counterRole: 'engineer',
    counterForm: 'deploy',
  },
];

export default COUNTER_CATALOG;
